### ISSUE TITLE
requests.exceptions.SSLError SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by CommanderAsdasd** [DaveTCode/confluence-python-lib#18]
Hi!
When I'm trying to create initial connection, I getting the following stacktrace:
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='confluence.federated.fds', port=443): Max retries exceeded with url: /confluence/rest/api/content/search?cql=ID%3D1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))
```

Our confluence have an expired certificate and I can't update it right now, is there any way to provide **verify=False** to requests without monkey-patching?

**Comment by DaveTCode** [comment]
Good idea. I've released 1.2.2 with the option of passing verify_confluence_certificate when creating a client, that then maps directly to the "verify" field on the requests library.
