### ISSUE TITLE
Bug in _put method

### ISSUE THREAD

**Issue by lucian97** [DaveTCode/confluence-python-lib#2]
Hi !
I was trying the create_content method and i noticed that at some point it is called the _put method. In this method you check if params is not None, but in my opinion you should check if expand is not None

**Comment by DaveTCode** [comment]
Do you mean https://github.com/DaveTCode/confluence-python-lib/commit/e2bdf571cc61f5e609a1c3b1bf98d0fb4a752866?

create_content goes via post rather than put so I'm not 100% sure what's broken. The above was clearly wrong but doesn't seem to match up to what you're saying.

**Comment by DaveTCode** [comment]
Oh nevermind, I see what you mean. I've fixed the issue on _post and _put which both mistakenly checked params instead of expand - as and when 0.12.3 gets through travis the fix will be on pypi. Thanks for spotting!

**Comment by DaveTCode** [comment]
FWIW 0.12.3 is now released on pypi and should include this fix

**Comment by lucian97** [comment]
Great! Thanks 👍 !
