### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by chhetripradeep** [DaveTCode/confluence-python-lib#21]
I am trying to play around with this library but I am getting authentication error 

```
import sys
from confluence.client import Confluence
from confluence.models.content import ContentType

def main():
    with Confluence('https://pradeepchhetri.atlassian.net/wiki', ('xxx@gmail.com', 'xxx')) as c:
        spaces = c.get_spaces(space_keys=['Core'])
        print(len(list(spaces)))

if __name__ == '__main__':
    sys.exit(main())
```
```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    sys.exit(main())
  File "test.py", line 8, in main
    print(len(list(spaces)))
  File "/Library/Python/2.7/site-packages/confluence/client.py", line 126, in _get_paged_results
    response = self._get(path, params, [])
  File "/Library/Python/2.7/site-packages/confluence/client.py", line 112, in _get
    Confluence._handle_response_errors(path, params, response)
  File "/Library/Python/2.7/site-packages/confluence/client.py", line 84, in _handle_response_errors
    raise ConfluenceAuthenticationError(path, params, response)
confluence.exceptions.authenticationerror.ConfluenceAuthenticationError: Authentication failure. This is most likely due to incorrect username/password
```
I am able to login with the same username and password in `https://id.atlassian.com/login`

Can you help me with some pointers to debug this issue.

Thank you.

**Comment by ExalDraen** [comment]
Just a quick suggestion to help you debug:

Inspect the `ConfluenceAuthenticationError` exception, in particular its `response` property - this is the full response as a `requests.Response` object. Check if the body of the response has any more information at to why a 401 (authentication error) was returned

Also, it looks like the Confluence instance you are trying to access is an atlassian cloud instance behind SSO - not sure if that works out of the box.

**Comment by chhetripradeep** [comment]
Thank you @ExalDraen - yes the confluence i am trying to authenticate is an atlassian cloud instance. Do you know if this library is only compatible with self-hosted atlassian instance ?

**Comment by chhetripradeep** [comment]
Yes after switching to self hosted atlassian, things worked for me. Thanks !!
