### ISSUE TITLE
Bug in add_attachments method

### ISSUE THREAD

**Issue by lucian97** [DaveTCode/confluence-python-lib#3]
In add_attachment method :
 return self._post_return_multiple(Content,
                                              '/content/{}/child/attachment'.format(content_id),
                                              params=params,
                                              files={'file': (file_name, f)},
                                              data={})

You should remove the slash before 'content', like this :  'content/{}/child/attachment'.format(content_id) , because further, when you will concatenate this string with self._api_base , you will optain something like this: http;//<'adress to confluence'>/rest/api//content/<'content id'>/child/attachment

**Comment by DaveTCode** [comment]
I've fixed that and one other occurrence of the same issue in 0.12.4 along with adding some integration tests to the attachment code. 

Thanks for spotting, fwiw I'd be happy to take PRs as well if you've got the time

**Comment by lucian97** [comment]
Yes, sure .
