### ISSUE TITLE
Example code does not work

### ISSUE THREAD

**Issue by aschepp** [DaveTCode/confluence-python-lib#4]
The example code does not work, c is NoneType

```
from confluence.client import Confluence
with Confluence('https://site:8080/confluence', ('user', 'pass')) as c:
    pages = c.search('ID=1')
```

The __enter__ method does not return self.
https://github.com/DaveTCode/confluence-python-lib/blob/master/confluence/client.py#L45

**Comment by DaveTCode** [comment]
Thanks, that was a bit dumb! I've just pushed a fixed version (0.13.1)
