### ISSUE TITLE
update_content arguments do not have default values

### ISSUE THREAD

**Issue by aschepp** [DaveTCode/confluence-python-lib#6]
https://github.com/DaveTCode/confluence-python-lib/blob/master/confluence/client.py#L214

The method update_content has optional arguments, but they do not have default values.

TypeError: update_content() missing 4 required positional arguments: 'status', 'new_title', 'new_parent', and 'new_status'

**Comment by aschepp** [comment]
Also, there are more bugs in update_content():
new_title is not optional
and _put_return_single tries to convert a json object to ContentType

**Comment by DaveTCode** [comment]
I'm very happy to accept PRs - there sure is plenty of low hanging fruit to fix ;)

Otherwise I'll try and get some time to spend on this over the weekend and build up more of the test suite so there's less of this nonsense.
